function searchFont() {
  const searchTerm = document.getElementById("font-search-input").value;
  applyFont(searchTerm);
}

function applyFont(fontFamily) {
  const styleElement = document.createElement("style");
  styleElement.textContent = `@import url('https://fonts.googleapis.com/css2?family=${fontFamily.replaceAll(
    " ",
    "+"
  )}:wght@400;700&display=swap');`;

  // Remove existing styles
  const existingStyleElement = document.querySelector(
    "style[data-font-styles]"
  );
  if (existingStyleElement) {
    existingStyleElement.remove();
  }

  // Add the new style element
  styleElement.setAttribute("data-font-styles", true);
  document.head.appendChild(styleElement);

  document.body.style.fontFamily = fontFamily;
}

const fontSuggestions = [
  "ABeeZee",
  "Abel",
  "Abril Fatface",
  "Aclonica",
  "Acme",
  "Actor",
  "Adamina",
  "Advent Pro",
  "Aguafina Script",
  "Akronim",
  "Aladin",
  "Aldrich",
  "Alef",
  "Alegreya",
  "Alegreya SC",
  "Alegreya Sans",
  "Alegreya Sans SC",
  "Alex Brush",
  "Alfa Slab One",
  "Alice",
  "Alike",
  "Alike Angular",
  "Allan",
  "Allerta",
  "Allerta Stencil",
  "Allura",
  "Almendra",
  "Almendra Display",
  "Almendra SC",
  "Amarante",
  "Amaranth",
  "Amatic SC",
  "Amethysta",
  "Amiri",
  "Anaheim",
  "Andada",
  "Andika",
  "Angkor",
  "Annie Use Your Telescope",
  "Anonymous Pro",
  "Antic",
  "Antic Didone",
  "Antic Slab",
  "Anton",
  "Arapey",
  "Arbutus",
  "Arbutus Slab",
  "Architects Daughter",
  "Archivo Black",
  "Archivo Narrow",
  "Arimo",
  "Arizonia",
  "Armata",
  "Artifika",
  "Arvo",
  "Asap",
  "Asset",
  "Astloch",
  "Asul",
  "Atomic Age",
  "Aubrey",
  "Audiowide",
  "Autour One",
  "Average",
  "Average Sans",
  "Averia Gruesa Libre",
  "Averia Libre",
  "Averia Sans Libre",
  "Averia Serif Libre",
  "Bad Script",
  "Balthazar",
  "Bangers",
  "Basic",
  "Battambang",
  "Baumans",
  "Bayon",
  "Belgrano",
  "Belleza",
  "BenchNine",
  "Bentham",
  "Berkshire Swash",
  "Bevan",
  "Bigelow Rules",
  "Bigshot One",
  "Bilbo",
  "Bilbo Swash Caps",
  "Biryani",
  "Bitter",
  "Black Ops One",
  "Bokor",
  "Bonbon",
  "Boogaloo",
  "Bowlby One",
  "Bowlby One SC",
  "Brawler",
  "Bree Serif",
  "Bubblegum Sans",
  "Bubbler One",
  "Buda",
  "Buenard",
  "Butcherman",
  "Butterfly Kids",
  "Cabin",
  "Cabin Condensed",
  "Cabin Sketch",
  "Caesar Dressing",
  "Cagliostro",
  "Calligraffitti",
  "Cambay",
  "Cambo",
  "Candal",
  "Cantarell",
  "Cantata One",
  "Cantora One",
  "Capriola",
  "Cardo",
  "Carme",
  "Carrois Gothic",
  "Carrois Gothic SC",
  "Carter One",
  "Caudex",
  "Cedarville Cursive",
  "Ceviche One",
  "Changa",
  "Chango",
  "Chau Philomene One",
  "Chela One",
  "Chelsea Market",
  "Chenla",
  "Cherry Cream Soda",
  "Cherry Swash",
  "Chewy",
  "Chicle",
  "Chivo",
  "Cinzel",
  "Cinzel Decorative",
  "Clicker Script",
  "Coda",
  "Coda Caption",
  "Codystar",
  "Combo",
  "Comfortaa",
  "Coming Soon",
  "Concert One",
  "Condiment",
  "Content",
  "Contrail One",
  "Convergence",
  "Cookie",
  "Copse",
  "Corben",
  "Courgette",
  "Cousine",
  "Coustard",
  "Covered By Your Grace",
  "Crafty Girls",
  "Creepster",
  "Crete Round",
  "Crimson Text",
  "Croissant One",
  "Crushed",
  "Cuprum",
  "Cutive",
  "Cutive Mono",
  "Dadhand",
  "Damion",
  "Dancing Script",
  "Dangrek",
  "Dawning of a New Day",
  "Days One",
  "Dekko",
  "Delius",
  "Delius Swash Caps",
  "Delius Unicase",
  "Della Respira",
  "Denk One",
  "Devonshire",
  "Dhurjati",
  "Didact Gothic",
  "Diplomata",
  "Diplomata SC",
  "Domine",
  "Donegal One",
  "Doppio One",
  "Dorsa",
  "Dosis",
  "Dr Sugiyama",
  "Droid Sans",
  "Droid Sans Mono",
  "Droid Serif",
  "Duru Sans",
  "Dynalight",
  "EB Garamond",
  "Eagle Lake",
  "Eater",
  "Economica",
  "Ek Mukta",
  "Electrolize",
  "El Messiri",
  "Elaine",
  "Elisia",
  "Elsie",
  "Elsie Swash Caps",
  "Emblema One",
  "Emilys Candy",
  "Engagement",
  "Englebert",
  "Enriqueta",
  "Erica One",
  "Esteban",
  "Euphoria Script",
  "Ewert",
  "Exo",
  "Exo 2",
  "Expletus Sans",
  "Fanwood Text",
  "Fascinate",
  "Fascinate Inline",
  "Faster One",
  "Fasthand",
  "Fauna One",
  "Federant",
  "Federo",
  "Felipa",
  "Fenix",
  "Finger Paint",
  "Fira Mono",
  "Fira Sans",
  "Fjalla One",
  "Fjord One",
  "Flamenco",
  "Flavors",
  "Fondamento",
  "Fontdiner Swanky",
  "Forum",
  "Francois One",
  "Freckle Face",
  "Fredericka the Great",
  "Fredoka One",
  "Freehand",
  "Fresca",
  "Frijole",
  "Fruktur",
  "Fugaz One",
  "GFS Didot",
  "GFS Neohellenic",
  "Gabriela",
  "Gafata",
  "Galdeano",
  "Galindo",
  "Gentium Basic",
  "Gentium Book Basic",
  "Geo",
  "Geostar",
  "Geostar Fill",
  "Germania One",
  "Gidugu",
  "Gilda Display",
  "Give You Glory",
  "Glass Antiqua",
  "Glegoo",
  "Gloria Hallelujah",
  "Goblin One",
  "Gochi Hand",
  "Gorditas",
  "Goudy Bookletter 1911",
  "Graduate",
  "Grand Hotel",
  "Gravitas One",
  "Great Vibes",
  "Griffy",
  "Gruppo",
  "Gudea",
  "Gurajada",
  "Habibi",
  "Halant",
  "Hammersmith One",
  "Hanalei",
  "Hanalei Fill",
  "Handlee",
  "Hanuman",
  "Happy Monkey",
  "Headland One",
  "Henny Penny",
  "Herr Von Muellerhoff",
  "Hind",
  "Holtwood One SC",
  "Homemade Apple",
  "Homenaje",
  "IM Fell DW Pica",
  "IM Fell DW Pica SC",
  "IM Fell Double Pica",
  "IM Fell Double Pica SC",
  "IM Fell English",
  "IM Fell English SC",
  "IM Fell French Canon",
  "IM Fell French Canon SC",
  "IM Fell Great Primer",
  "IM Fell Great Primer SC",
  "Iceberg",
  "Iceland",
  "Imprima",
  "Inconsolata",
  "Inder",
  "Indie Flower",
  "Inika",
  "Irish Grover",
  "Istok Web",
  "Italiana",
  "Italianno",
  "Jacques Francois",
  "Jacques Francois Shadow",
  "Jaldi",
  "Jim Nightshade",
  "Jockey One",
  "Jolly Lodger",
  "Josefin Sans",
  "Josefin Slab",
  "Joti One",
  "Judson",
  "Julee",
  "Julius Sans One",
  "Junge",
  "Jura",
  "Just Another Hand",
  "Just Me Again Down Here",
  "Kalam",
  "Kameron",
  "Kantumruy",
  "Karla",
  "Karma",
  "Kaushan Script",
  "Kavoon",
  "Kdam Thmor",
  "Keania One",
  "Kelly Slab",
  "Kenia",
  "Khand",
  "Khmer",
  "Khula",
  "Kite One",
  "Knewave",
  "Kotta One",
  "Koulen",
  "Kranky",
  "Kreon",
  "Kristi",
  "Krona One",
  "La Belle Aurore",
  "Laila",
  "Lakki Reddy",
  "Lancelot",
  "Lateef",
  "Lato",
  "League Script",
  "Leckerli One",
  "Ledger",
  "Lekton",
  "Lemon",
  "Libre Baskerville",
  "Life Savers",
  "Lilita One",
  "Lily Script One",
  "Limelight",
  "Linden Hill",
  "Lobster",
  "Lobster Two",
  "Londrina Outline",
  "Londrina Shadow",
  "Londrina Sketch",
  "Londrina Solid",
  "Lora",
  "Love Ya Like A Sister",
  "Loved by the King",
  "Lovers Quarrel",
  "Luckiest Guy",
  "Lusitana",
  "Lustria",
  "Macondo",
  "Macondo Swash Caps",
  "Magra",
  "Maiden Orange",
  "Mako",
  "Mallanna",
  "Mandali",
  "Marcellus",
  "Marcellus SC",
  "Marck Script",
  "Margarine",
  "Marko One",
  "Marmelad",
  "Martel",
  "Martel Sans",
  "Marvel",
  "Mate",
  "Mate SC",
  "Maven Pro",
  "McLaren",
  "Meddon",
  "MedievalSharp",
  "Medula One",
  "Megrim",
  "Meie Script",
  "Merienda",
  "Merienda One",
  "Merriweather",
  "Merriweather Sans",
  "Metal",
  "Metal Mania",
  "Metamorphous",
  "Metrophobic",
  "Michroma",
  "Mila Script",
  "Milonga",
  "Miltonian",
  "Miltonian Tattoo",
  "Miniver",
  "Miss Fajardose",
  "Modak",
  "Modern Antiqua",
  "Molle",
  "Monda",
  "Monofett",
  "Monoton",
  "Monsieur La Doulaise",
  "Montaga",
  "Montez",
  "Montserrat",
  "Montserrat Alternates",
  "Montserrat Subrayada",
  "Moul",
  "Moulpali",
  "Mountains of Christmas",
  "Mouse Memoirs",
  "Mr Bedfort",
  "Mr Dafoe",
  "Mr De Haviland",
  "Mrs Saint Delafield",
  "Bebas neue",
  "Nunito",
  "Nunito Sans",
  // Add more font suggestions as needed
];

document
  .getElementById("font-search-input")
  .addEventListener("input", function () {
    const inputValue = this.value.toLowerCase();
    const dataList = document.getElementById("font-suggestions");
    dataList.innerHTML = "";

    const matchingFonts = fontSuggestions.filter((font) =>
      font.toLowerCase().includes(inputValue)
    );

    matchingFonts.forEach((font) => {
      const option = document.createElement("option");
      option.value = font;
      dataList.appendChild(option);
    });
  });
function handleKeyPress(event) {
  if (event.key === "Enter") {
    searchFont();
  }
}
function uploadFont(event) {
  const fileInput = event.target;
  const fileList = fileInput.files;

  if (fileList.length > 0) {
    const fontFile = fileList[0];
    // Perform logic to load and use the uploaded font
    console.log("Uploaded font:", fontFile.name);
    applyFont(fontFile.name, fontFile);
  }
}

function applyFont(fontName, fontFile) {
  const fontStyles = document.getElementById("custom-font-styles");

  if (fontFile) {
    // Upload and use the custom font file
    const fontUrl = URL.createObjectURL(fontFile);
    fontStyles.innerHTML = `@font-face {
            font-family: '${fontName}';
            src: url('${fontUrl}') format('woff2');
        }`;
  } else {
    // Use a Google Font
    fontStyles.innerHTML = `@import url('https://fonts.googleapis.com/css2?family=${fontName.replaceAll(
      " ",
      "+"
    )}&display=swap');`;
  }

  // Apply the font to the sections
  const sections = document.querySelectorAll(".section");
  sections.forEach((section) => {
    section.style.fontFamily = `'${fontName}', sans-serif`;
  });
}
